-- MySQL Script generated by MySQL Workbench
-- dom 29 ago 2021 19:01:49 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema procurovagas_db
-- -----------------------------------------------------
-- database from procurovagas

-- -----------------------------------------------------
-- Schema procurovagas_db
--
-- database from procurovagas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `procurovagas_db` DEFAULT CHARACTER SET utf8 ;
USE `procurovagas_db` ;

-- -----------------------------------------------------
-- Table `procurovagas_db`.`vagas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `procurovagas_db`.`vagas` (
  `vagas_id` INT NOT NULL AUTO_INCREMENT,
  `origem` INT NOT NULL,
  `cnpj` CHAR(19) NULL,
  `razao_social` VARCHAR(60) NULL,
  `nome_recrutador` VARCHAR(45) NULL,
  `local` VARCHAR(45) NULL,
  `desc_empresa` MEDIUMTEXT NULL,
  `tipo_vaga` VARCHAR(25) NULL,
  `cargo` VARCHAR(50) NULL,
  `n_vagas` INT NULL DEFAULT 1,
  `forma_trabalho` VARCHAR(20) NULL,
  `cidade` VARCHAR(50) NULL,
  `estado` CHAR(2) NULL,
  `desc_vaga` LONGTEXT NULL,
  `qualificacao` LONGTEXT NULL,
  `caracteristicas` VARCHAR(45) NULL,
  `remuneracao` DECIMAL(10,2) NULL,
  `beneficios` MEDIUMTEXT NULL,
  `jornada` VARCHAR(70) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT 'CURRENT_TIMESTAMP',
  `updated_at` TIMESTAMP NULL,
  `tempo_vaga` DATETIME NULL,
  PRIMARY KEY (`vagas_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `procurovagas_db`.`emails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `procurovagas_db`.`emails` (
  `emails_id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(80) NOT NULL,
  `tipo_email` INT NOT NULL,
  `vagas_id` INT NULL,
  `config_subscribe` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`emails_id`, `vagas_id`),
  INDEX `fk_emails_vagas_idx` (`vagas_id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  CONSTRAINT `fk_emails_vagas`
    FOREIGN KEY (`vagas_id`)
    REFERENCES `procurovagas_db`.`vagas` (`vagas_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
